"""initial tables

Revision ID: beee355a1e42
Revises: 
Create Date: 2026-06-07 13:20:17.213113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beee355a1e42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('meal_plan',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('num_days', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('day_plan',
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plan.plan_id'], ),
    sa.PrimaryKeyConstraint('day_id')
    )
    op.create_table('meal',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('time_to_cook', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day_plan.day_id'], ),
    sa.PrimaryKeyConstraint('meal_id')
    )
    op.create_table('ingredients',
    sa.Column('ing_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.meal_id'], ),
    sa.PrimaryKeyConstraint('ing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients')
    op.drop_table('meal')
    op.drop_table('day_plan')
    op.drop_table('meal_plan')
    op.drop_table('users')
    # ### end Alembic commands ###
