"""add recipe to meal

Revision ID: de7e57c4dc04
Revises: beee355a1e42
Create Date: 2026-06-08 17:10:19.719090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7e57c4dc04'
down_revision: Union[str, Sequence[str], None] = 'beee355a1e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('recipe', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal', 'recipe')
    # ### end Alembic commands ###
